# @package _global_
defaults:
  - _self_
  - paths: default.yaml
  - hydra: default.yaml
  - datamodule: binary_cifar10.yaml

# Output directory is generated dynamically on each run
# following the pattern ${paths.log_dir}/${task_name}/runs/${run_name}
task_name: eval
run_name: ${now:%Y-%m-%d}_${now:%H-%M-%S}

# seed for random number generators in pytorch, numpy and python.random
seed: 12345

result_path: ???
